sudo: false
dist: trusty
language: generic

cache:
  timeout: 1000
  directories:
    - $HOME/.stack/
    - $HOME/.local/bin/
    - .stack-work/

branches:
  only:
    - master

# matrix:
#   include:
#   - env: ARGS=""
#   - env: ARGS="--stack-yaml stack-7.10.yaml"
#   - ghc: 7.10.3
#   - ghc: 8.0.2

install: # command output is hidden as they complete

  # if any command fails, end the travis script
  - set -e

  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH

  # Or, fetch latest stack if a stack is not already installed. Saves a little time/fragility.
  - if [[ ! -x ~/.local/bin/stack ]]; then travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'; chmod a+x ~/.local/bin/stack; fi

  - which stack
  - type -a stack
  - stack --version
  - echo ~
  - ~/.local/bin/stack --version

  # GHC
  - stack setup
  - stack exec -- ghc --version

script:
  - stack build
  - stack test
