name:                sortee
version:             0.1.0.1
github:              "b123400/sortee"
license:             GPL-3
author:              "b123400"
maintainer:          "i@b123400.net"
copyright:           "2019 b123400"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Generate string for sort key
category:            Sorting

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/b123400/sortee#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  sortee-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sortee
    - hspec >=2.0.0
    - QuickCheck >= 2.10.1 && < 3.0
    - HUnit
